### ISSUE TITLE
Question about docking

### ISSUE THREAD

**Issue by Pacane** [Mastermindzh/dotfiles#1]
Hi, I just came to find your dotfiles, thanks for the great example btw.

I had a question about how you manage your docking system. Basically, I'm wondering if you have to restart X or your computer at all so that the DPI scaling changes take effect with your docked.sh/undocked.sh scripts.

Finally, I also use an XPS laptop, and I wanted to know if you have multiple monitors with different DPIs, and if so, have you found a way to get things to display decently (because of the DPI difference between the 2 monitors for example)

Thanks again, and great job with your dotfiles.

**Comment by Mastermindzh** [comment]
Hey Pacane,

I don't have to restart x. I simply run the script, unplug and i3 refreshes. After that I'll have to restart other apps that don't adjust their scaling automatically (like chrome / terminals) if I want them to scale properly.
I usually do this when it's needed, my chat app really only has UI to change between chats and I don't use that (use keyboard instead) so I won't reload that but when I go to code something I'll **have** to reload the window first if I want to get anything done:stuck_out_tongue: 

Yes, I used to use different DPI monitors and that did present *some* difficulty seeing as X only has 1 scaling settings (and apps can't figure it out themselves either, they all read from a parameter)

In the end I settled on 2560x1440 for both displays seeing as I have the laptop at an angle and slightly away from me. My laptop display only serves as a terminal holder though and basically always has 4 terminals on it:

- a logbook
- a random terminal to run commands
- some kind of monitoring, either specific or gtop/htop
- a docker runner terminal, usually runs the docker-compose file of the project I'm currently working on.

All other work is done on the physically larger display.

In reality though, switching between workspaces doesn't happen *that* often and it's usually just for a short while. If I have to go to a meeting I'll just spin up a fresh browser and a new terminal to take notes and leave the rest as-is. When I get back to my main working area I'll simply dock again and all stuff will be properly scaled still.

The only time I have to switch for an extended period of time is the weekend, I'll either go through all apps and restart them as needed or reboot at this point, though it's usually the former seeing as I don't like rebooting... :)

Any other questions? feel free to ask!

**Comment by Pacane** [comment]
Are you sure that changing values is .Xresources (and doing `xrdb -merge` on it) and then restarting your apps, does makes them take into account the new values? This doesn't seem to work properly for me.

**Comment by Pacane** [comment]
btw, just a side note, I'm not using i3, but XMonad instead.

**Comment by Mastermindzh** [comment]
Yeah, I'm sure that works because I use it regularly.

I've made a video (with the cell... at night.. sorry, capture devices don't like resolution changes) to show you that it works (might be processing still):

[![youtubevid](https://img.youtube.com/vi/DjxADDWFjAE/0.jpg)](https://www.youtube.com/watch?v=DjxADDWFjAE)

**Comment by Pacane** [comment]
I have things under control now.

Thanks to you, your config and your help! :) :+1:

**Comment by Mastermindzh** [comment]
No problem mate, enjoy!
